modules/common/controller.py
modules/common/pythonpayload.py
modules/common/supportfiles.py
modules/payloads/auxiliary/pyinstaller_wrapper.py
modules/payloads/python/meterpreter/bind_tcp.py
modules/payloads/python/meterpreter/rev_tcp.py
setup/setup.sh

I just added a new module : python/meterpreter/bind_tcp based on the existing reverse_tcp one.

- Added a bind_tcp python meterpreter module

---

modules/payloads/go/meterpreter/rev_http.py
modules/payloads/go/meterpreter/rev_https.py
modules/payloads/go/meterpreter/rev_tcp.py
modules/payloads/go/shellcode_inject/virtual.py

Pure go shellcode_inject and meterpreter/rev_tcp

Add Go payloads

---

setup/setup.sh

+ Add Silent/Quiet/Automated/Unattended Install option to `setup/bash.sh` (`--silent`).
+ Kali Linux doesn't have `wine64` in the repos, so trying to use it will causes errors. It now checks before calling.

Add silent install option '--silent' & Misc fixes

---

config/update.py
modules/common/controller.py
modules/common/messages.py
modules/common/supportfiles.py
setup/setup.sh
tools/vt-notify/vt-notify.rb

I personally don't like it how the screen clears after each menu reloads (messes up terminal history when scrolling up). Proof is below:
```
root@kali ~/Veil-Evasion$ python Veil-Evasion.py                                                                                                                         master 
=========================================================================
Veil-Evasion | [Version]: 2.21.2
=========================================================================
[Web]: https://www.veil-framework.com/ | [Twitter]: @VeilFramework
=========================================================================
=========================================================================
Veil-Evasion | [Version]: 2.21.2 …
```

Reloading menus without refresh/clear

---

modules/common/controller.py
modules/common/messages.py

Rather than displaying the local/relative path - it will display the full path (useful for Kali-Linux users who have it installed). 
...Started to error number codes, making it easier to debug/understand where the issue is.

Display full path to file

---

modules/payloads/python/shellcode_inject/aes_encrypt_HTTPKEY_Request.py

Adds useragent to self.required_options, original code used the urllib default useragent, which would stand out to incident responders.

Added useragent option

---

modules/common/supportfiles.py
tools/pyobfuscate/LICENSE
tools/pyobfuscate/pyobfuscate

Hi,
I added pyobfuscate (https://github.com/astrand/pyobfuscate) to obfuscate python payloads right before compile them into exe file.
This way, there is no need to obfuscate them manually and Veil code might be more human readable.
What do you think about this?
Regards

python payloads + pyobfuscate

---

setup/setup.sh

Added support in for Fedora 22 so I can use it on my own setup without requiring Debian/Ubuntu. So far, I've only tested it with Fedora 22, but the beginnings are there to have it work with CentOS and RHEL. I would have to do testing on it first before I add those to the version checks.

Add support for Fedora 22+ to setup

---

modules/payloads/auxiliary/macro_converter.py

This auxiliary module takes output from our powershell shellcodeinject/virtual module and converts it into text usable for a macro based attack.  This is purely based off of khr0x40sh's blog post and I simply just automated it in this module.

Macro converter

---

modules/payloads/python/shellcode_inject/aes_encrypt_HTTPKEY_Request.py

-Fixed ctypes import for AV
-Fixed Except statement for payload

Fix and change ctypes

---

README.md

I've been using Veil-Evasion via RPC server and had to make many attempts to understand how to use it. This documentation may help other users with a more in-depth description on how to utilize this tool.

Added documentation about using RPC server with Veil-Evasion

---

CHANGELOG
modules/common/messages.py
modules/payloads/perl/shellcode_inject/flat.py

New Perl module for Veil-Evasion's January 2016 V-Day

Added module for January v-day release

---

setup/install-addons.sh
setup/setup.sh

+ Add a splash of colour to `setup.sh`
+ Updates for kali 2/rolling

Add colour to setup.sh

---

modules/common/supportfiles.py

Fix for bug

---

modules/payloads/python/shellcode_inject/aes_encrypt.py
modules/payloads/python/shellcode_inject/arc_encrypt.py
modules/payloads/python/shellcode_inject/base64_substitution.py
modules/payloads/python/shellcode_inject/des_encrypt.py
modules/payloads/python/shellcode_inject/flat.py
modules/payloads/python/shellcode_inject/letter_substitution.py

This pull request adds obfuscation to some of the python payloads in Veil-Evasion.

Updated obfuscation

---

setup/setup.sh

Setup: Fix architecture detection for Kali 32bit

---

Veil-Evasion.py

Here I employ a strategy that looks for gadgets used for command injection as well items unlikely to appear in legitimate input.

msfvenom filtering alternative strategy

---

CHANGELOG
config/update.py
modules/common/messages.py

Thanks to @sbrun, this should help Kali users.  This pull request is specifically in relation to issue #302.

Patch provided by @sbrun to help with kali compatibility

---

CHANGELOG
modules/common/messages.py
modules/payloads/native/hyperion.py
modules/payloads/native/pe_scrambler.py

This fixes the hyperion and pescrambler bugs

---

CHANGELOG
modules/common/messages.py
modules/common/supportfiles.py

No longer have runw.exe error message

---

modules/common/shellcode.py

parameter is not validated in the following code, it will cause crash when user input does not include "=" mark.
[>] Enter any extra msfvenom options (syntax: OPTION1=value1 or -OPTION2=value2): a a

parameter validate

---

CHANGELOG
config/update.py
modules/common/messages.py

This update fixes the pyinstaller path based on the latest setup script changes.

Updated update.py

---

setup/setup.sh

Fix ubuntu setup issue

---

setup/setup.sh

Pretty minor fix but I'm troubleshooting other setup issues and the red prompt I kept getting was bugging me :D

Fix missing color escape.
